import Head from "next/head";

export default function SignUp() {
	return (
	  <div >
		<Head>
		  <title>NG - Signup</title>
		  <meta name="description" content="Generated by create next app" />
		  <link rel="icon" href="/favicon.ico" />
		</Head>
		  <h1>TEste</h1>
		  <h2>TEste</h2>
  
	  
	  </div>
	)
  }